### ISSUE TITLE
Not working with release of Loxone 9.0.9.26

### ISSUE THREAD

**Issue by jdstroy70** [Sroose/homebridge-loxone-ws#16]
homebridge-loxone-ws doesn't work anymore since update 9.0.9.26. I noticed that one way status update from Loxone to HomeKit worked but after some reboots of the homebridge pi this functionality is also broken.

**Comment by COMHOME** [comment]
correct, the lightcontroller2 got a new uid after converting.

**Comment by jdstroy70** [comment]
Is there a way to fix it?

**Comment by Nexus2k** [comment]
+1 doesn't work anymore. As far as I understand they changed the Authentication mechanism: https://www.loxone.com/dede/wp-content/uploads/sites/2/2016/08/0900_Communicating-with-the-Miniserver.pdf "Tokens have been introduced in Loxone Config 9. They are used for authentication instead of passwords. Tokens can expire, be revoked without changing the password - and they allow for a much more refined permission handling. See separate section for details on how to handle tokens."
I guess we need a way to create and refresh the tokens.

**Comment by Nexus2k** [comment]
This will need to be fixed in https://github.com/alladdin/node-lox-ws-api as that part does the Authentication.

**Comment by zllimit** [comment]
is it fixed now?

**Comment by idoodler** [comment]
I just created pull request #18 which includes the correct node-lox-ws-api dependency

**Comment by Sroose** [comment]
@idoodler Thank you for the help! PR is merged

**Comment by twischi** [comment]
Until [npm Version](https://www.npmjs.com/package/homebridge-loxone-ws) is updated to 1.0.3 you can install it directly from github see #14
