### ISSUE TITLE
Filter with more than 100 items

### ISSUE THREAD

**Issue by maxi07** [Sroose/homebridge-loxone-ws#27]
Hi there, got everything up and running so far except for the 100 items limit. Not really sure how to filter out some widgets or modules. Can you please provide an example?

**Comment by chiefjoejj** [comment]
Hi Maxi,
create a new user-group in Loxone Config called "Intergration" with a new user "homebridge" within this group. Then change every widget/module to "users" and only the widgets/modules you also want to use within homebridge to "all".

That is quite an effort since you have a lot of devices within Loxone but you can use the "program"-view to group devices within one "page". That made things a lot easier for me - and "only" cost around an hour regrouping 5k+ items.  Hope that helps :D

Cheers
Jay

**Comment by maxi07** [comment]
Thanks for the reply, I will check this out.

Cheers,
Max

--
Maximilian Krause
+491758831466
